[package]
name = "secrets-app-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
apdu-dispatch = { version = "0.4",  optional = true }
flexiber = { version = "0.2.0", features = ["derive", "heapless"] }
heapless = "0.9"
heapless-bytes = "0.5"
hex-literal = "0.3"
iso7816 = "0.2"
serde = { version = "1", default-features = false }
trussed = { version = "0.1.0", features = ["virt", "verbose-tests"] }
ctaphid-dispatch = { version = "0.4", optional = true }
clap = { version = "3.0.0", features = ["cargo", "derive"] }
clap-num = "1.0.0"
pretty_env_logger = "0.4.0"

trussed-auth = "0.5"
trussed-auth-backend = "0.1"


[dependencies.secrets-app]
path = ".."

[features]
default = ["ctaphid-dispatch", "apdu-dispatch"]


# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false

[[bin]]
name = "corpus-viewer"
path = "corpus-viewer/corpus-viewer.rs"
test = false
doc = false


[patch.crates-io]
trussed = { git = "https://github.com/trussed-dev/trussed.git", rev = "0f8df68be879acdde1f8cf428c11e5d29692a47b" }
trussed-auth-backend = { git = "https://github.com/trussed-dev/trussed-auth.git", tag = "v0.5.0" }

